In [38]:
import pandas as pd
df_train = pd.read_csv('/content/drive/MyDrive/DA Assignment Dataset/train_data.csv')
df_test = pd.read_csv('/content/drive/MyDrive/DA Assignment Dataset/test_data.csv')

UTILITY FUNCTIONS

In [3]:
def check_mixed_types(df, column_name):
    """Checks if a column in a DataFrame has mixed data types."""

    unique_types = df[column_name].apply(type).unique()
    # print(unique_types)
    return len(unique_types)

def drop_rows_with_float(df, column_name):
    """Drops rows where the specified column has integer type data."""
    df_filtered = df[df[column_name].apply(type) != float ]
    return df_filtered

FILTER TRAIN SET

In [39]:
features = df_train.columns
for feature in features:
    mixed_types = check_mixed_types(df_train, feature)
    # print(mixed_types)
    if mixed_types > 1:
        print(f"Column '{feature}' has '{mixed_types}' data types.")

df_filtered = drop_rows_with_float(df_train, 'maritalstatus')
df_filtered = drop_rows_with_float(df_filtered, 'race')
df_filtered = drop_rows_with_float(df_filtered, 'sex')

df_train_filtered = df_filtered
features = df_filtered.columns
for feature in features:
    mixed_types = check_mixed_types(df_train_filtered, feature)
    if mixed_types > 1:
        print(f"Column '{feature}' has '{mixed_types}' data types.")

Column 'maritalstatus' has '2' data types.
Column 'race' has '2' data types.
Column 'sex' has '2' data types.

FILTER TEST SET

In [40]:
df_filtered = drop_rows_with_float(df_test, 'maritalstatus')
df_filtered = drop_rows_with_float(df_filtered, 'race')
df_filtered = drop_rows_with_float(df_filtered, 'sex')

df_test_filtered = df_filtered
features = df_filtered.columns
for feature in features:
    mixed_types = check_mixed_types(df_test_filtered, feature)
    if mixed_types > 1:
        print(f"Column '{feature}' has '{mixed_types}' data types.")

In [8]:
catogorical_features = ['workclass', 'education', 'maritalstatus', 'occupation', 'relationship', 'race', 'sex', 'native']
continuous_features = ['age', 'educationno', 'capitalgain', 'capitalloss', 'hoursperweek']

In [41]:
X_train = df_train_filtered.drop('Possibility', axis=1)
y_train = df_train_filtered['Possibility']
X_test = df_test.drop('Possibility', axis=1)
y_test = df_test['Possibility']

In [42]:
X_categorical_train = X_train.drop(continuous_features, axis=1)
X_continuous_train = X_train[continuous_features]

X_categorical_test = X_test.drop(continuous_features, axis=1)
X_continuous_test = X_test[continuous_features]

ONE HOT ENCODING

In [43]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

columns_to_encode = ['race', 'maritalstatus','occupation','relationship','native','workclass']

ohe = OneHotEncoder(sparse_output=False,dtype=np.int64,drop='first')
X_categorical_prev = X_categorical_train
X_categorical_new = ohe.fit_transform(X_categorical_train[columns_to_encode])
X_categorical_new = pd.DataFrame(X_categorical_new, columns=ohe.get_feature_names_out(columns_to_encode))
X_categorical = pd.concat([X_categorical_prev, X_categorical_new], axis=1)
X_categorical.drop(columns_to_encode, axis=1, inplace=True)
X_categorical.sample(5)

,education,sex,race_Asian-Pac-Islander,race_Black,race_Other,race_White,maritalstatus_Married-AF-spouse,maritalstatus_Married-civ-spouse,maritalstatus_Married-spouse-absent,maritalstatus_Never-married,...,native_Trinadad&Tobago,native_United-States,native_Vietnam,native_Yugoslavia,workclass_Local-gov,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,workclass_State-gov,workclass_Without-pay
8190,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
9089,HS-grad,Male,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
9570,10th,Male,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
16632,HS-grad,Female,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,HS-grad,Male,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [44]:
X_categorical['sex'] = X_categorical['sex'].str.strip().str.lower()
X_categorical['sex'] = X_categorical['sex'].map({'male': 1, 'female': 0})
X_categorical.sample(5)

,education,sex,race_Asian-Pac-Islander,race_Black,race_Other,race_White,maritalstatus_Married-AF-spouse,maritalstatus_Married-civ-spouse,maritalstatus_Married-spouse-absent,maritalstatus_Never-married,...,native_Trinadad&Tobago,native_United-States,native_Vietnam,native_Yugoslavia,workclass_Local-gov,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,workclass_State-gov,workclass_Without-pay
16576,HS-grad,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
10042,HS-grad,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2593,11th,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2536,HS-grad,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
9155,HS-grad,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

ORDINAL ENCODING (if required for "education" column)

In [32]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Preschool','Average','Good']])
# oe.fit(X_categorical['education'])
# X_train = oe.transform(X_train)
X_categorical_train['education'].value_counts()

education
HS-grad         6574
Some-college    4574
Bachelors       3460
Masters         1089
Assoc-voc        884
Assoc-acdm       720
11th             713
10th             569
7th-8th          382
Prof-school      378
9th              319
Doctorate        264
12th             261
5th-6th          183
1st-4th          102
Preschool         33
Name: count, dtype: int64