In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/missing_values-SalaryData_Train.csv')
print(df.head())

   age         workclass  education  educationno       maritalstatus  \
0   39         State-gov  Bachelors           13       Never-married
1   50  Self-emp-not-inc  Bachelors           13  Married-civ-spouse
2   38           Private    HS-grad            9            Divorced
3   53           Private       11th            7  Married-civ-spouse
4   28           Private  Bachelors           13  Married-civ-spouse

          occupation   relationship   race     sex  capitalgain  capitalloss  \
0       Adm-clerical  Not-in-family  White    Male         2174            0
1    Exec-managerial        Husband  White    Male            0            0
2  Handlers-cleaners  Not-in-family  White    Male            0            0
3  Handlers-cleaners        Husband  Black    Male            0            0
4     Prof-specialty           Wife  Black  Female            0            0

   hoursperweek         native Possibility
0          40.0  United-States       <=0.5
1          13.0  United-States       <=0.5
2          40.0  United-States       <=0.5
3          40.0  United-States       <=0.5
4          40.0           Cuba       <=0.5

In [3]:
def encodeLabel(y):
  if y == '<=0.5':
    return 0
  else:
    return 1

df['Possibility'] = df['Possibility'].apply(encodeLabel)
df.head()

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Possibility
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40.0,United-States,0
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13.0,United-States,0
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40.0,United-States,0
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40.0,United-States,0
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40.0,Cuba,0

In [4]:
df.tail()

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Possibility
30156,27,Private,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38.0,United-States,0
30157,40,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,NaN,NaN,0,0,40.0,United-States,1
30158,58,Private,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40.0,United-States,0
30159,22,Private,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20.0,United-States,0
30160,52,Self-emp-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40.0,United-States,1

In [5]:
df.shape

(30161, 14)

In [7]:
from sklearn.model_selection import train_test_split

X = df.drop('Possibility', axis=1)
y = df['Possibility']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Creating train & test dataframes.
train_df = pd.concat([X_train, y_train], axis=1)
test_df = pd.concat([X_test, y_test], axis=1)
print(train_df.shape)
print(test_df.shape)

train_df.to_csv('train_data_new.csv', index=False)
test_df.to_csv('test_data_new.csv', index=False)

(24128, 14)
(6033, 14)